version: "3"
services:
  webapp:
    image: your_webapp_image
    ports:
      - "8080:8080"
    networks:
      - zap_network

  zap:
    image: owasp/zap2docker-stable
    ports:
      - "8090:8090"
    networks:
      - zap_network
    command: "zap.sh -daemon -host 0.0.0.0 -port 8090"

  web:
    image: artisans-nook
    container_name: artisans-nook-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - zap_network

networks:
  zap_network:
    driver: bridge