name: Deploy

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/artisans-nook:latest .

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/artisans-nook:latest

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@56.228.0.252 'DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} bash -s' < deploy-script.sh

    - name: Run OWASP ZAP Scan
      run: |
        docker run --user root -v ${{ github.workspace }}:/zap/wrk \
        ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t https://artisansnook.pp.ua/ \
        -r zap_report.html
        echo "OWASP ZAP scan completed."
      env:
        TZ: Europe/Moscow

    - name: Check Report Generation
      run: |
        if [ -f zap_report.html ]; then
          echo "ZAP report successfully generated."
        else
          echo "ZAP report not found."
          exit 1
        fi

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap_report.html

    - name: Display Scan Result
      if: always()
      run: cat zap_report.html
      